### ISSUE TITLE
Игнорируется форматирование

### ISSUE THREAD

**Issue by PatakIN13** [Djaler/evil-bot#165]
При выполнении команды `/sed` игнорируется форматирование исходного сообщения, а так же если оно есть при выполнении команды.
![Снимок экрана 2021-05-30 144857](https://user-images.githubusercontent.com/56484009/120099711-7806ec80-c156-11eb-881c-f10b0111df28.png)

**Comment by Djaler** [comment]
Невозможно реализовать в общем виде
