### ISSUE TITLE
Replace Markdown with MarkdownV2

### ISSUE THREAD

**Issue by InsanusMokrassar** [Djaler/evil-bot#21]
I have reviewed code in this library a little bit and find that here `MarkdownParseMode` was used. So, currently it is recommended to use `MarkdownV2ParseMode` (or simply `MarkdownV2` which is the same) due to the fact, that `Markdown` do not support including of styles inside of other styles and have no underline and strikethrough styles on Telegram side (it is emulated on the library side with special unicode characters)

**Comment by Djaler** [comment]
Resolved in 5d970d487c2417d0cea61955d190a794facf0685
