### ISSUE TITLE
Ненужная прослойка TelegramClient

### ISSUE THREAD

**Issue by Djaler** [Djaler/evil-bot#91]
Этот компонент был написан в то врермя, когда для отправки запросов нужно было создавать объекты и дёргать RequestsExecutor.execute. Сейчас сам RequestsExecutor предоставляет методы-расширения для всего, что нужно, поэтому от лишней прослойки можно избавиться, дёргая в напрямую RequestsExecutor

**Comment by tujh2** [comment]
Беру

**Comment by Djaler** [comment]
Сделано в #92
